name: EndMcExercise
main: fr.flappy.endmc.ExercisePlugin
version: 1.0
commands:
  player:
    description: Start an exercise
    permission: endmc.exercise
  givetoplayer:
    description: Give an exercise to a player
    permission: endmc.exercise